remote_theme: mmistakes/minimal-mistakes@4.24.1 # Example stable version
plugins:
  - jekyll-remote-theme

title: "Pet Breed Recognizer"
description: "An image classification model that classifies 25 different breeds of pets around the world."
author: 
  name: "Farhan Noor Dehan"
